/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tyfone_csc_communication_SDIOCommunication */

#ifndef _Included_com_tyfone_csc_communication_SDIOCommunication
#define _Included_com_tyfone_csc_communication_SDIOCommunication
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tyfone_csc_communication_SDIOCommunication
 * Method:    initializeCSC
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_tyfone_csc_communication_SDIOCommunication_initializeCSC
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_tyfone_csc_communication_SDIOCommunication
 * Method:    getATR
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tyfone_csc_communication_SDIOCommunication_getATR
  (JNIEnv *, jobject);

/*
 * Class:     com_tyfone_csc_communication_SDIOCommunication
 * Method:    setPowerOn
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tyfone_csc_communication_SDIOCommunication_setPowerOn
  (JNIEnv *, jobject);

/*
 * Class:     com_tyfone_csc_communication_SDIOCommunication
 * Method:    setPowerOff
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tyfone_csc_communication_SDIOCommunication_setPowerOff
  (JNIEnv *, jobject);

/*
 * Class:     com_tyfone_csc_communication_SDIOCommunication
 * Method:    setRFOn
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tyfone_csc_communication_SDIOCommunication_setRFOn
  (JNIEnv *, jobject);

/*
 * Class:     com_tyfone_csc_communication_SDIOCommunication
 * Method:    setRFOff
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tyfone_csc_communication_SDIOCommunication_setRFOff
  (JNIEnv *, jobject);

/*
 * Class:     com_tyfone_csc_communication_SDIOCommunication
 * Method:    writeToCard
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tyfone_csc_communication_SDIOCommunication_writeToCard
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tyfone_csc_communication_SDIOCommunication
 * Method:    getFirmwareVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tyfone_csc_communication_SDIOCommunication_getFirmwareVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_tyfone_csc_communication_SDIOCommunication
 * Method:    finalizeCSC
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tyfone_csc_communication_SDIOCommunication_finalizeCSC
  (JNIEnv *, jobject);

/*
 * Class:     com_tyfone_csc_communication_SDIOCommunication
 * Method:    readFromPollingFile
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_tyfone_csc_communication_SDIOCommunication_readFromPollingFile
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
